---
- name: AWS CFN Boostrap | Ubuntu | Install Python PIP
  apt:
    name: python-pip

- name: AWS CFN Bootstrap | Ubuntu | Install Python Modules
  pip: 
    name: pystache argparse python-daemon requests

- name: AWS CFN Boostrap | Ubuntu | Download the aws-cfn-bootstrap from AWS
  get_url: 
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz 
    dest: /tmp/
  
- name: AWS CFN Bootstrap | Ubuntu | Unarchive aws-cfn-bootstrap
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/aws-cfn-bootstrap-latest.tar.gz
  
- name: AWS CFN Bootstrap | Ubuntu | Install AWS CFN Bootstrap Module
  easy_install: 
    name: /tmp/aws-cfn-bootstrap-latest.tar.gz
  
- name: AWS CFN Bootstrap | Ubuntu | Add cfn-hup to init.d scripts
  file: 
    src: /tmp/aws-cfn-bootstrap-1.4/init/ubuntu/cfn-hup
    dest: /etc/init.d/cfn-hup