---
- name: CFN Boostrap | Ubuntu | Install python-pip
  apt: name=python-pip state=installed
  when: ansible_os_family == "Debian"
  
- name: CFN Boostrap | RedHat | Install python-pip
  yum: name=python-pip state=installed
  when: ansible_os_family == "RedHat"

- name: CFN Bootstrap | Install Python Modules
  pip: name={{ item }} state=present
  with_items:
    - pystache
    - argparse
    - python-daemon
    - requests
  
- name: CFN Boostrap | Download the aws-cfn-bootstrap from AWS
  get_url: 
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz 
    dest: /tmp/

- name: CFN Bootstrap | Unarchive aws-cfn-bootstrap
  unarchive:
    copy: no
    src: /tmp/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz
    dest: /opt/
  
- name: CFN Bootstrap | Install CFN Bootstrap Module
  easy_install: name=/tmp/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz
  
- name: CFN Bootstrap | RedHat | Install CFN Bootstrap Init
  command: cp /opt/aws-cfn-bootstrap-{{ version }}/init/redhat/cfn-hup /etc/init.d/cfn-hup
  args:
    creates: /etc/init.d/cfn-hup
  when: ansible_os_family == "RedHat"

- name: CFN Bootstrap | Ubuntu | Install CFN Bootstrap Init
  command: cp /opt/aws-cfn-bootstrap-{{ version }}/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
  args:
    creates: /etc/init.d/cfn-hup
  when: ansible_os_family == "Debian"

- name: CFN Bootstrap | Set cfn-hup permissions
  action: file path=/etc/init.d/cfn-hup mode=0755
  
- name: Create /opt/aws/bin/ directory
  action: file path=/opt/aws/bin/ state=directory
  
- name: Create link file from /usr/bin/cfn-hub to /opt/aws/bin/cfn-hup
  action: file src=/usr/bin/cfn-hup dest=/opt/aws/bin/cfn-hup state=link