---
- name: AWS CFN Boostrap | RedHat | Install Python PIP
  yum:
    name: python-pip
    
- name: AWS CFN Bootstrap | RedHat | Install Python Modules
  pip: 
    name: pystache argparse python-daemon requests

- name: AWS CFN Boostrap | RedHat | Download the aws-cfn-bootstrap from AWS
  get_url: 
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz 
    dest: /tmp/

- name: AWS CFN Bootstrap | RedHat | Unarchive aws-cfn-bootstrap
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/aws-cfn-bootstrap-latest.tar.gz
  
- name: AWS CFN Bootstrap | RedHat | Install AWS CFN Bootstrap Module
  easy_install: 
    name: /tmp/aws-cfn-bootstrap-latest.tar.gz
  
- name: AWS CFN Bootstrap | RedHat | Add cfn-hup to init.d scripts
  file:
    src: /tmp/aws-cfn-bootstrap-1.4/init/redhat/cfn-hup
    dest: /etc/init.d/cfn-hup