---
- name: AWS CFN Boostrap | RedHat | Install Python PIP
  yum:
    name: python-pip
    
- name: AWS CFN Bootstrap | RedHat | Install Python Modules
  pip: 
    name: pystache argparse python-daemon requests

- name: AWS CFN Boostrap | RedHat | Download the aws-cfn-bootstrap from AWS
  get_url: 
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz 
    dest: /tmp/

- name: AWS CFN Bootstrap | RedHat | Unarchive aws-cfn-bootstrap
  unarchive:
    copy: no
    src: /tmp/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz
    dest: /opt/
    creates: /opt/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz
  
- name: AWS CFN Bootstrap | RedHat | Install AWS CFN Bootstrap Module
  easy_install: name=/opt/aws-cfn-bootstrap-{{ pkg_version }}.tar.gz

- command: cp /opt/aws-cfn-bootstrap-{{ version }}/init/redhat/cfn-hup /etc/init.d/cfn-hup
  creates: /etc/init.d/cfn-hup
- file: path=/etc/init.d/cfn-hup mode=0755
- file: path=/opt/aws/bin/ state=directory
- file: src=/usr/bin/cfn-hup dest=/opt/aws/bin/cfn-hup state=link